import { useCallback, useEffect, useState } from 'react'
import { isAxiosError } from 'axios'
import { useAuth } from '../auth/useAuth'
import { Alert, FormField } from '../components/ui/FormField'
import { Input } from '../components/ui/Input'
import { Button } from '../components/ui/Button'
import { PageHeader } from '../components/ui/PageHeader'
import { configuracaoService } from '../services/configuracaoService'
import type { ConfiguracaoRequest, ConfiguracaoResponse } from '../types/configuracao'
import '../styles/configuration.css'

const defaults: ConfiguracaoRequest = { plMaximo: 15, dyMinimo: 6, roeMinimo: 15, dividaPatrimonioMaximo: 1, margemLiquidaMinimo: 20, retornoPreco: 6 }
const fields: Array<{ key: keyof ConfiguracaoRequest; label: string; hint: string; unit?: string }> = [
  { key: 'plMaximo', label: 'P/L máximo', hint: 'Limite de preço em relação ao lucro.' }, { key: 'dyMinimo', label: 'Dividend Yield mínimo', hint: 'Rendimento anual mínimo.', unit: '%' }, { key: 'roeMinimo', label: 'ROE mínimo', hint: 'Retorno mínimo sobre patrimônio.', unit: '%' }, { key: 'dividaPatrimonioMaximo', label: 'Dívida / Patrimônio máximo', hint: 'Limite de endividamento.' }, { key: 'margemLiquidaMinimo', label: 'Margem líquida mínima', hint: 'Eficiência mínima de lucro.', unit: '%' }, { key: 'retornoPreco', label: 'Retorno desejado', hint: 'Retorno anual desejado.', unit: '%' },
]

export function ConfigurationPage() {
  const { user } = useAuth(); const [values, setValues] = useState<ConfiguracaoRequest>(defaults); const [exists, setExists] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const [errors, setErrors] = useState<Partial<Record<keyof ConfiguracaoRequest, string>>>({})
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(null); try { const response = await configuracaoService.obter(user.idUsuario); setValues(toRequest(response)); setExists(true) } catch (error: unknown) { if (isAxiosError(error) && error.response?.status === 404) { setValues(defaults); setExists(false) } else if (isAxiosError(error) && error.response?.status === 403) setError('Você não tem permissão para acessar esta configuração.')
    else setError('Não foi possível carregar seus critérios. Tente novamente.') } finally { setLoading(false) } }, [user])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const next = validate(values); setErrors(next); setSuccess(false); if (Object.keys(next).length || !user) return; setSaving(true); setError(null); try { const response = exists ? await configuracaoService.alterar(user.idUsuario, values) : await configuracaoService.adicionar(user.idUsuario, values); setValues(toRequest(response)); setExists(true); setSuccess(true) } catch (error: unknown) { setError(message(error)) } finally { setSaving(false) } }
  if (loading) return <><PageHeader title="Configuração" description="Defina os critérios que orientam sua análise." /><section className="configuration-skeleton" aria-busy="true"><span /><span /><span /><span /><span /><span /></section></>
  if (error && !exists) return <><PageHeader title="Configuração" description="Defina os critérios que orientam sua análise." /><section className="empty-state"><h2>Não foi possível abrir sua configuração.</h2><p>{error}</p><Button onClick={() => void load()}>Tentar novamente</Button></section></>
  return <><PageHeader title="Seus critérios de análise" description="Estes parâmetros ajudam o InvestLens a organizar uma análise alinhada à sua estratégia." /><form className="configuration-form" onSubmit={save}><div className="configuration-heading"><h2>Fundamentos e retorno</h2><p>Use valores em formato humano. Percentuais como 6% devem ser informados como 6.</p></div><div className="configuration-grid">{fields.map((field) => <FormField key={field.key} label={field.label} htmlFor={field.key} error={errors[field.key]}><div className="configuration-input"><Input id={field.key} type="text" inputMode="decimal" value={String(values[field.key])} disabled={saving} aria-invalid={Boolean(errors[field.key])} aria-describedby={errors[field.key] ? `${field.key}-error` : undefined} onChange={(event) => setValues((current) => ({ ...current, [field.key]: parse(event.target.value) }))} />{field.unit && <span>{field.unit}</span>}</div><small>{field.hint}</small></FormField>)}</div>{error && <Alert>{error}</Alert>}{success && <p className="configuration-success" role="status">Critérios salvos com sucesso.</p>}<div className="configuration-actions"><Button type="submit" loading={saving}>{exists ? 'Salvar alterações' : 'Criar configuração'}</Button><span>{exists ? 'Suas alterações serão aplicadas aos próximos usos da plataforma.' : 'Você poderá ajustar estes critérios a qualquer momento.'}</span></div></form></>
}
function parse(value: string) { const normalized = value.trim().replace(',', '.'); return normalized === '' ? Number.NaN : Number(normalized) }
function validate(values: ConfiguracaoRequest) { const errors: Partial<Record<keyof ConfiguracaoRequest, string>> = {}; fields.forEach(({ key }) => { if (!Number.isFinite(values[key])) errors[key] = 'Informe um número válido.'; else if (key === 'retornoPreco' ? values[key] <= 0 : values[key] < 0) errors[key] = key === 'retornoPreco' ? 'Informe um valor maior que zero.' : 'Informe zero ou um valor positivo.' }); return errors }
function toRequest(response: ConfiguracaoResponse): ConfiguracaoRequest { const { plMaximo, dyMinimo, roeMinimo, dividaPatrimonioMaximo, margemLiquidaMinimo, retornoPreco } = response; return { plMaximo, dyMinimo, roeMinimo, dividaPatrimonioMaximo, margemLiquidaMinimo, retornoPreco } }
function message(error: unknown) { if (!isAxiosError(error)) return 'Não foi possível salvar. Tente novamente.'; if (error.response?.status === 403) return 'Você não tem permissão para alterar esta configuração.'; if (error.response?.status === 409) return 'A configuração já existe. Atualize a página e tente novamente.'; if (error.response?.status === 400) return 'Revise os valores informados.'; return 'Não foi possível salvar. Tente novamente.' }
