import { useState } from 'react'
import { isAxiosError } from 'axios'
import { ArrowRight, BarChart3, Eye, EyeOff, Filter, LockKeyhole, PieChart, UserRound } from 'lucide-react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/useAuth'
import logoSimple from '../../../imgs/logo_simples.png'
import backgroundLogin from '../../../imgs/background_login.png'
import '../styles/login.css'

export function LoginPage() { const { isAuthenticated, login }=useAuth();const nav=useNavigate();const loc=useLocation();const [email,setEmail]=useState('');const [senha,setSenha]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');if(isAuthenticated)return <Navigate to="/" replace/>;const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!email||!senha){setError('Informe e-mail e senha.');return}setBusy(true);setError('');try{await login({email,senha});setSenha('');nav((loc.state as {from?:string})?.from||'/',{replace:true})}catch(e){setError(isAxiosError(e)&&e.response?.status===401?'Credenciais inválidas.':'Não foi possível acessar sua conta. Tente novamente.')}finally{setBusy(false)}};return <main className="login-page"><section className="login-intro"><Link className="login-brand" to="/"><img src={logoSimple} alt=""/><b>Invest<span>Lens</span></b></Link><div className="login-intro-copy"><h1>Análise inteligente<br/>para suas decisões.</h1><p>Explore dados das empresas da B3, aplique seus filtros e encontre oportunidades com base em indicadores fundamentalistas.</p></div><div className="login-signals"><Benefit icon={<BarChart3/>} title="Dados completos" text="Informações das empresas da B3 em um só lugar."/><Benefit icon={<Filter/>} title="Filtros avançados" text="Selecione os indicadores que fazem sentido para a sua estratégia."/><Benefit icon={<PieChart/>} title="Análises claras" text="Visualize e compare empresas de forma simples e objetiva."/></div><img className="login-background" src={backgroundLogin} alt=""/></section><section className="login-access"><div className="login-card"><div className="login-card-brand"><img src={logoSimple} alt=""/><b>Invest<span>Lens</span></b></div><header><h2>Bem-vindo de volta!</h2><p>Faça login para acessar sua conta.</p></header><form onSubmit={submit}><label>E-mail<div className="input-icon"><UserRound/><input className="form-control" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Digite seu e-mail"/></div></label><label>Senha<div className="input-icon password-control"><LockKeyhole/><input className="form-control" type={show?'text':'password'} autoComplete="current-password" value={senha} onChange={e=>setSenha(e.target.value)} placeholder="Digite sua senha"/><button type="button" onClick={()=>setShow(!show)} aria-label="Mostrar ou ocultar senha">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="login-options"><label><input type="checkbox"/> Lembrar de mim</label><a href="#ajuda">Esqueceu sua senha?</a></div>{error&&<p className="ui-alert">{error}</p>}<button className="login-submit ui-button ui-button-primary" disabled={busy}><span>{busy?'Entrando com segurança':'Entrar'}</span><ArrowRight/></button></form><footer>Versão 1.0.0</footer></div></section></main>}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article><span className="signal-icon">{icon}</span><div><h2>{title}</h2><p>{text}</p></div></article>}
